### ISSUE TITLE
Cpp Syntax highlighting

### ISSUE THREAD

**Issue by dpiparo** [dpiparo/ROOTaaS#1]
We need to replace the highlighting with the cpp one when the cpp transformer is active and when we are in a cpp/dcl cell.

**Comment by etejedor** [comment]
We should check what the %%javascript and %%R magics do: right after you type %%javascript in the cell, it starts to parse the Javascript syntax.

**Comment by etejedor** [comment]
Highlighting in the notebook is applied in two different scenarios:
1. Interactive highlighting: words get highlighted in the notebook as you type. This is managed by the notebook's JS modules + CodeMirror JS language modules.
2. Static highlighting: when exporting the notebook as e.g. an HTML page, the necessary tags are inserted in the HTML code to highlight the syntax. This is managed by a notebook preprocessor + pygments lexers.

**Comment by etejedor** [comment]
I have committed the code necessary to enable interactive C++ highlighting in cells marked with the %%cpp and %%dcl magics.
Next I will address the static highlighting.

**Comment by dpiparo** [comment]
Is it possible to treat all cells after switching to C++ with the toCpp() method as if they all were marked with the %%cpp magic?

**Comment by etejedor** [comment]
I need to look more into that. Apart from the magics, there should be a way to change the default syntax highlighting (Python), both for the interactive and static cases.

**Comment by etejedor** [comment]
I committed a preprocessor to do the C++ highlighting in static HTML notebooks.

In order to enable it, the IPython configuration file must contain the following line:
c.Exporter.preprocessors = [ 'ROOTaaS.export.cpphighlighter.CppHighlighter' ]

There are two ways to generate the HTML notebooks:
- From the Jupyter notebook: make sure the line above is in your notebook config file, and go to File --> Download as --> HTML.
- Using nbconvert:
  ipython nbconvert --to html --config my_config_file.py my_notebook.ipynb

**Comment by etejedor** [comment]
Next thing pending: interactive c++ syntax switching when doing ROOT.toCpp() and toPython()

**Comment by etejedor** [comment]
Interactive highlight switching implemented and committed.
